# Generated by Django 2.2.4 on 2022-08-07 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0005_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='link',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default='artist', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='firstdjango.Artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist',
            field=models.CharField(default='idk', max_length=255),
        ),
    ]
