# Generated by Django 2.2.4 on 2022-08-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0007_auto_20220806_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
    ]
