# Generated by Django 2.2.4 on 2022-08-07 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0008_auto_20220806_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='firstdjango.Artist'),
        ),
    ]
