# Generated by Django 2.2.4 on 2022-08-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0010_auto_20220806_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=255),
        ),
    ]
