# Generated by Django 2.2.4 on 2022-08-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0011_auto_20220806_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Albums',
        ),
    ]
