# Generated by Django 2.2.4 on 2022-08-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0013_albums_artist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('link', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='albums',
            name='artist_image',
            field=models.CharField(default='you a bitch', max_length=255),
        ),
    ]
