# Generated by Django 2.2.4 on 2022-08-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0016_auto_20220806_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='tracklist_id',
            field=models.IntegerField(default=0),
        ),
    ]
