# Generated by Django 2.2.4 on 2022-08-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0017_tracks_tracklist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='track',
            new_name='title',
        ),
    ]
