# Generated by Django 2.2.4 on 2022-08-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0018_auto_20220806_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='RYM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
    ]
