# Generated by Django 2.2.4 on 2022-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0021_auto_20220807_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ryan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=255)),
            ],
        ),
    ]
