# Generated by Django 2.2.4 on 2022-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0022_ryan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ryan',
            name='artist',
            field=models.CharField(default='idk', max_length=255),
            preserve_default=False,
        ),
    ]
