# Generated by Django 2.2.4 on 2022-08-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0025_randperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreatScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=255)),
            ],
        ),
    ]
