# Generated by Django 2.2.4 on 2022-08-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0027_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='rating',
            field=models.CharField(default='idk', max_length=500),
            preserve_default=False,
        ),
    ]
