# Generated by Django 2.2.4 on 2022-08-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0031_mela_mlecbp_mlecp_mlecrbp_mlecrtbp_mlep_sms_utstms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLECBP',
        ),
        migrations.DeleteModel(
            name='MLECP',
        ),
        migrations.DeleteModel(
            name='MLECRBP',
        ),
        migrations.DeleteModel(
            name='MLECRTBP',
        ),
    ]
